apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.app_name }}
    type: {{ .Values.deployment.labels.type }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      type: {{ .Values.deployment.labels.type }}
      app: {{ .Values.app_name }}
  template:
    metadata:
      name: {{ .Values.deployment.container.name }}  
      labels:
        app: {{ .Values.app_name }}
        type: {{ .Values.deployment.labels.type }}
    spec:
      containers:
        - name : {{ .Values.app_name }}
          image: "{{ .Values.deployment.container.image }}:{{ .Values.deployment.container.tag }}"
          ports:
          - containerPort: {{ .Values.deployment.container.port }}
          env:
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_BUCKET
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_SECRET_ACCESS_KEY
          - name: REGION_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: REGION_NAME

